### ISSUE TITLE
when copy/pasting if a normal DOT is selected, it will error

### ISSUE THREAD

**Issue by raysunvfx** [raysunvfx/Input-Fetcher#14]
Traceback (most recent call last):
  File "/home/rays/.nuke/rsCopyPaste.py", line 100, in rsPaste
    createOutputFromInput(node)
  File "/home/rays/.nuke/rsCopyPaste.py", line 55, in createOutputFromInput
    output['id'].setValue(inputNode['id'].getValue())
NameError: knob id does not exist

to fix this, validate if the dot is an INPUT/OUTPUT, if not, ignore

**Comment by raysunvfx** [comment]
fixed by validating if node is valid INPUT and 'DOT'

**Comment by raysunvfx** [comment]
reopened

same problem

**Comment by raysunvfx** [comment]
nvm just using older version of copy/paste lol
